default_install_hook_types: [pre-commit, commit-msg]
exclude: ^vendor/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-renovate
      - id: check-jsonschema
        name: Validate DevContainer Config
        args:
          [
            --schemafile,
            "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json",
          ]
        files: ^\.devcontainer\.json$
        types_or: [json]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.0
    hooks:
      - id: actionlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - json
          - yaml

  - repo: local
    hooks:
      - id: tflint
        name: tflint
        entry: tflint
        language: system
        files: (\.tf|\.tfvars)$
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
