name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4.0.0

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@73e0dc723dad863ee2d6ac8be6f3671b43da1801 # 1.3.16
